---
apiVersion: v1
kind: Service
metadata:
  name: erp-accounts-accounts-be
  labels: 
    app: erp-accounts-accounts-be-app
spec:
  selector:
    app: erp-accounts-accounts-be-app
    tier: backend
  type: NodePort
  ports:
    - port: 11195                #container port
      targetPort: 11195           #Pod port
      nodePort: 32092       #If type is NodePort then use nodePort   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-accounts-accounts-be
  namespace: ecgcbackend
  labels: 
    app: erp-accounts-accounts-be-app   
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: erp-accounts-accounts-be-app
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 0
  template: 
    metadata: 
      labels: 
        app: erp-accounts-accounts-be-app
        tier: backend
      name: erp-accounts-accounts-be
    spec:
      containers: 
        - image: docker-registry.cdacmumbai.in:443/erp-accounts-accounts-be.jar:latest
          imagePullPolicy: Always        
          name: erp-accounts-accounts-be-container
          ports:
          - containerPort: 11195
          readinessProbe:
            tcpSocket:
              port: 11195
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
               port: 11195
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 5
#          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "250m"
#            limits:
#              memory: "128Mi"
#              cpu: "500m" 		  
#          ports: 
#           - containerPort: 80
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: "sit-secured"
#      nodeSelector:
#	   size:medium	
      dnsConfig:
        searches:
          - ecgc.svc.cluster.local
          - ecgcbackend.svc.cluster.local
